(()=>{
const svg=`<svg viewBox="0 0 96 96" role="img" aria-label="Pipe fumante de Wonq" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="wpWood" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#c68a50"/><stop offset=".52" stop-color="#71432f"/><stop offset="1" stop-color="#321f24"/></linearGradient><radialGradient id="wpAura"><stop offset="0" stop-color="#69a99b" stop-opacity=".22"/><stop offset="1" stop-color="#a47bb4" stop-opacity="0"/></radialGradient><filter id="wpGlow"><feDropShadow dx="0" dy="0" stdDeviation="3" flood-color="#d3a65e" flood-opacity=".55"/></filter></defs><circle cx="48" cy="52" r="41" fill="url(#wpAura)"/><g filter="url(#wpGlow)"><path class="pipe-smoke smoke-one" d="M68 35c-12-8 7-15-2-25"/><path class="pipe-smoke smoke-two" d="M76 35c11-10-6-17 5-26"/><path class="pipe-smoke smoke-three" d="M62 35c-5-8 0-13 4-18"/><path d="M10 66c22 1 41-3 57-14" fill="none" stroke="url(#wpWood)" stroke-width="8" stroke-linecap="round"/><path d="M12 63c21 0 38-4 53-13" fill="none" stroke="#e0b675" stroke-width="2" stroke-linecap="round" opacity=".7"/><path d="M62 43h25l-3 20c-2 13-10 20-20 18-10-2-15-11-11-21z" fill="url(#wpWood)" stroke="#d3a65e" stroke-width="2"/><ellipse cx="74.5" cy="43" rx="13" ry="5" fill="#171116" stroke="#d3a65e" stroke-width="2.3"/><ellipse cx="74.5" cy="43" rx="8" ry="2.4" fill="#ef9b51"/><path d="M7 62h12v9H9c-6 0-7-7-2-9z" fill="#21171a" stroke="#b77c49" stroke-width="2"/></g></svg>`;
const style=document.createElement('style');style.textContent=`
/* header-silas-exact */
.identity:after{content:none!important}.signature-icon{position:absolute;right:12px;top:50%;width:96px;height:96px;transform:translateY(-50%) rotate(-4deg);pointer-events:none;filter:drop-shadow(0 8px 18px #000b);z-index:1}.signature-icon svg{width:100%;height:100%;display:block;overflow:visible}.identity .eyebrow,.identity h1,.identity p,.identity .motto{position:relative;z-index:2}.pipe-smoke{fill:none;stroke:#d8e5e1;stroke-width:3.2;stroke-linecap:round;stroke-dasharray:30;stroke-dashoffset:30;opacity:0}.smoke-two{stroke:#d2b9dc}#concState{display:none!important}
.turn-conc{min-width:0;border:1px solid #645486;background:linear-gradient(145deg,#211b2d,#14121d);border-radius:11px;padding:7px 10px;text-align:left;cursor:pointer;overflow:hidden;color:inherit}.turn-conc small{display:block;color:#b8a8df;font-size:.65rem;text-transform:uppercase;letter-spacing:.07em}.turn-conc b{display:block;color:#ded3fb;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.turn-conc.none{border-color:#443f43;background:#171518}.turn-conc.none small,.turn-conc.none b{color:var(--muted)}.turn-conc:not(.none){box-shadow:inset 0 0 0 1px #a08ad733,0 0 15px #8c6dc522}
@media(min-width:768px){.top{display:grid!important;grid-template-columns:1.4fr 2fr!important;gap:14px!important;align-items:stretch!important}.identity{padding:18px 118px 18px 18px!important;min-height:0!important;overflow:hidden!important}.identity h1{font-size:clamp(2rem,5vw,3.6rem)!important;line-height:.95!important;margin:.25rem 0 .55rem!important}.identity p{font-size:inherit!important;line-height:1.45!important;white-space:normal!important;overflow:visible!important}.identity .motto{margin-top:9px!important;font-size:.9rem!important;white-space:normal!important;overflow:visible!important}.dashboard{padding:12px!important;display:grid!important;grid-template-columns:2fr repeat(5,1fr)!important;grid-auto-rows:auto!important;gap:8px!important;align-items:stretch!important;overflow:visible!important}.dashboard>.stat,.dashboard>.hpstat{display:block!important;grid-column:auto!important;grid-row:auto!important;min-width:0!important;padding:10px!important;border-radius:12px!important;text-align:left!important;overflow:hidden!important}.dashboard>.stat:nth-child(n+7){display:none!important}.dashboard>.hpstat>small{display:block!important;white-space:normal!important}.dashboard .hpgrid{display:grid!important;grid-column:auto!important;grid-row:auto!important;grid-template-columns:1fr 1fr!important;gap:5px!important;margin-top:5px!important}.dashboard .hp-tools{display:grid!important;grid-column:auto!important;grid-row:auto!important;grid-template-columns:64px 1fr 1fr!important;gap:5px!important;margin-top:6px!important}.dashboard>.stat b{font-size:1.35rem!important;line-height:1.35!important;white-space:nowrap!important}.dashboard>.stat small{font-size:.66rem!important;line-height:1.35!important;letter-spacing:.07em!important}.dashboard .number{box-sizing:border-box!important;width:100%!important;height:auto!important;min-height:0!important;padding:6px!important;font-size:inherit!important}.dashboard .hp-tools button{height:auto!important;min-height:32px!important;padding:4px!important;font-size:.7rem!important}}
@media(min-width:1101px){.turnbar{grid-template-columns:auto repeat(4,minmax(68px,1fr)) minmax(92px,.85fr) minmax(112px,1fr) auto auto auto!important}}
@media(min-width:768px) and (max-width:1100px){.dashboard{grid-template-columns:2fr repeat(3,1fr)!important}.turnbar{grid-template-columns:repeat(4,1fr)!important}.turn-conc{grid-column:span 2;min-height:58px!important;padding:8px 11px!important}.turn-conc b{white-space:normal!important;overflow:visible!important;text-overflow:clip!important;line-height:1.2!important;overflow-wrap:anywhere}.turnbar .next{grid-column:span 2}}
@media(max-width:767px){.signature-icon{width:76px;height:76px;right:6px}.identity{padding-right:82px!important}.turn-conc{grid-column:span 2}}
@media(prefers-reduced-motion:no-preference){.pipe-smoke{animation:wonqSmoke 3.5s ease-in-out infinite}.smoke-two{animation-delay:1.1s}.smoke-three{animation-delay:2.1s}@keyframes wonqSmoke{0%{stroke-dashoffset:30;opacity:0;transform:translateY(4px)}24%{opacity:.82}72%{stroke-dashoffset:0;opacity:.48}100%{stroke-dashoffset:-18;opacity:0;transform:translateY(-10px)}}}@media(prefers-reduced-motion:reduce){.pipe-smoke{stroke-dashoffset:0;opacity:.58}}
`;document.head.appendChild(style);
const mount=()=>{const id=document.querySelector('.identity');if(!id)return false;id.querySelector('.signature-icon')?.remove();const d=document.createElement('div');d.className='signature-icon';d.innerHTML=svg;id.appendChild(d);return true};
if(!mount()){const o=new MutationObserver(()=>{if(mount())o.disconnect()});o.observe(document.documentElement,{childList:true,subtree:true})}

const mountTurnConcentration=()=>{const bar=document.getElementById('turnbar')||document.querySelector('.turnbar');const source=document.getElementById('concState');if(!bar||!source||document.getElementById('turnConcentration'))return false;const button=document.createElement('button');button.type='button';button.id='turnConcentration';button.className='turn-conc none';button.title='Gérer la concentration';button.innerHTML='<small>Concentration</small><b>Aucune</b>';const anchor=document.getElementById('nextTurn')||bar.querySelector('.next');bar.insertBefore(button,anchor||null);const sync=()=>{const raw=source.textContent.trim();const value=(raw.includes(':')?raw.slice(raw.indexOf(':')+1):raw).trim()||'Aucune';button.querySelector('b').textContent=value;button.classList.toggle('none',value.toLowerCase()==='aucune')};button.addEventListener('click',()=>source.click());new MutationObserver(sync).observe(source,{childList:true,subtree:true,characterData:true,attributes:true});sync();return true};if(!mountTurnConcentration()){const tcObserver=new MutationObserver(()=>{if(mountTurnConcentration())tcObserver.disconnect()});tcObserver.observe(document.documentElement,{childList:true,subtree:true})}


const quickStyle=document.createElement('style');quickStyle.textContent=`
/* quick-slots-ui */
.quick-slots{width:100%;display:flex;align-items:center;gap:9px;margin:0 0 10px;padding:7px 10px;border:1px solid #554c48;border-radius:12px;background:linear-gradient(135deg,#1c181be8,#171518e8);color:var(--ink);text-align:left;box-shadow:inset 0 1px #ffffff08}.quick-slots-label{font-size:.68rem;text-transform:uppercase;letter-spacing:.08em;color:var(--muted);white-space:nowrap}.quick-slots-values{display:flex;gap:6px;flex-wrap:wrap;margin-left:auto}.quick-slot{border:1px solid #715d3b;border-radius:8px;padding:4px 7px;background:#211912;font-size:.76rem;white-space:nowrap}.quick-slot b{color:var(--gold);font-size:.84rem}
#slotDots.slot-pills{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}#slotDots.slot-pills>.row{position:relative;display:flex;gap:0;margin:0;border:1px solid #715d3b;border-radius:8px;background:#211912;overflow:hidden}#slotDots.slot-pills>.row>b,#slotDots.slot-pills>.row>.dot{display:none!important}.slot-controls{display:flex;align-items:stretch}.slot-adjust,.slot-summary{min-height:34px;border:0;background:transparent;color:var(--ink);padding:4px 7px}.slot-adjust{width:31px;padding:0;color:var(--gold);font-weight:900}.slot-adjust:first-child{border-right:1px solid #715d3b66}.slot-adjust:last-child{border-left:1px solid #715d3b66}.slot-adjust:disabled{opacity:.28;cursor:not-allowed}.slot-summary{display:flex;align-items:center;white-space:nowrap;font-size:.78rem}.slot-summary b{margin-left:4px;color:var(--gold);font-size:.88rem}
@media(max-width:767px){.quick-slots{padding:6px 8px;gap:6px}.quick-slots-label{font-size:.61rem}.quick-slots-values{gap:4px}.quick-slot{padding:3px 6px;font-size:.7rem}}
`;document.head.appendChild(quickStyle);
const mountQuickSlots=()=>{const section=document.getElementById('combat'),source=document.getElementById('slotDots');if(!section||!source||document.getElementById('quickSpellSlots'))return false;const box=document.createElement('button');box.type='button';box.id='quickSpellSlots';box.className='quick-slots';box.title='Ouvrir les sorts';box.innerHTML='<span class="quick-slots-label">Emplacements</span><span class="quick-slots-values"></span>';section.insertBefore(box,section.firstChild);const sync=()=>{const rows=[...source.querySelectorAll('.row')];box.querySelector('.quick-slots-values').innerHTML=rows.map(row=>{const level=row.querySelector('b')?.textContent||'';const dots=[...row.querySelectorAll('.dot')];const current=dots.filter(d=>d.classList.contains('on')).length;return '<span class="quick-slot">'+level+' <b>'+current+'/'+dots.length+'</b></span>'}).join('')};box.addEventListener('click',()=>document.querySelector('.nav button[data-view="spells"]')?.click());new MutationObserver(sync).observe(source,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});sync();return true};
if(!mountQuickSlots()){const qsObserver=new MutationObserver(()=>{if(mountQuickSlots())qsObserver.disconnect()});qsObserver.observe(document.documentElement,{childList:true,subtree:true})}

const mountSlotPills=()=>{const box=document.getElementById('slotDots');if(!box)return false;box.classList.add('slot-pills');const sync=()=>{[...box.querySelectorAll(':scope>.row')].forEach((row,index)=>{const dots=[...row.querySelectorAll('.dot')];if(!dots.length)return;let controls=row.querySelector('.slot-controls');if(!controls){controls=document.createElement('div');controls.className='slot-controls';controls.innerHTML=`<button type="button" class="slot-adjust slot-minus" aria-label="Dépenser un emplacement de niveau ${index+1}">−</button><span class="slot-summary">N${index+1} <b></b></span><button type="button" class="slot-adjust slot-plus" aria-label="Restaurer un emplacement de niveau ${index+1}">+</button>`;row.appendChild(controls);controls.querySelector('.slot-minus').onclick=()=>{const current=dots.filter(d=>d.classList.contains('on')).length;if(current>0)dots[current-1].click()};controls.querySelector('.slot-plus').onclick=()=>{const current=dots.filter(d=>d.classList.contains('on')).length;if(current<dots.length)dots[current].click()}}const current=dots.filter(d=>d.classList.contains('on')).length;controls.querySelector('.slot-summary b').textContent=`${current}/${dots.length}`;controls.querySelector('.slot-minus').disabled=current===0;controls.querySelector('.slot-plus').disabled=current===dots.length})};new MutationObserver(sync).observe(box,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});sync();return true};if(!mountSlotPills()){const spObserver=new MutationObserver(()=>{if(mountSlotPills())spObserver.disconnect()});spObserver.observe(document.documentElement,{childList:true,subtree:true})}

const fav=document.createElement('link');fav.rel='icon';fav.type='image/svg+xml';fav.href='data:image/svg+xml,'+encodeURIComponent(svg);document.head.appendChild(fav);
})();
